; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32doit-devkit-v1
workspace_dir = ${sysenv.TMPDIR}/PedalinoMini

[common]
lib_deps = 
	bxparks/AceButton@1.10.1
	bblanchon/ArduinoJson@7.2.0
	esphome/AsyncTCP-esphome@2.1.4
	esphome/ESPAsyncWebServer-esphome@3.2.2
	fastled/FastLED@3.7.4
	d03n3rfr1tz3/HC-SR04@1.1.2
	esphome/Improv@1.2.3
	majicdesigns/MD_REncoder@1.0.1
	h2zero/NimBLE-Arduino@1.4.2
	https://github.com/CNMAT/OSC@3.5.8
	dxinteractive/ResponsiveAnalogRead@1.2.1
	bodmer/TFT_eSPI@2.5.33
	fortyseveneffects/MIDI Library@5.0.2
	lathoub/AppleMIDI@3.3.0
	lathoub/BLE-MIDI@2.2
	lathoub/ipMIDI@1.0.3
	ryokosaka/Hello Drum@0.7.7
	adafruit/Adafruit ADS1X15@2.5.0
build_flags = 
	-D PEDALINO_MINI
	-D PLATFORMIO_ENV=$PIOENV
	-D DEBUG_ESP_PORT=Serial
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN
	-D DIAGNOSTIC
	-D NVS
	-D SMARTCONFIG
	-D WPS
build_flags_esp32 = 
	-D SSD1306WIRE
build_flags_esp32-ble = 
	-D NOWIFI
	-D SSD1306WIRE
build_flags_esp32-wifi = 
	-D NOBLE
	-D SSD1306WIRE
build_flags_heltec_wifi_kit_32 = 
	-D HELTEC_WIFI_KIT_32
	-D BATTERY
build_flags_ttgo_t_eight = 
	-D TTGO_T_EIGHT
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
build_flags_ttgo_t_eight-ble = 
	-D TTGO_T_EIGHT
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D NOWIFI
build_flags_ttgo_t_eight-wifi = 
	-D TTGO_T_EIGHT
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D NOBLE
build_flags_lilygo_t_display = 
	-D BATTERY
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER
	-D TFT_SDA_READ
	-D TFT_WIDTH=135
	-D TFT_HEIGHT=240
	-D CGRAM_OFFSET
	-D TFT_MOSI=19
	-D TFT_SCLK=18
	-D TFT_CS=5
	-D TFT_DC=16
	-D TFT_RST=23
	-D TFT_BL=4
	-D TFT_BACKLIGHT_ON=1
	-D LOAD_GLCD
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	-D SPI_FREQUENCY=40000000
	-D SPI_READ_FREQUENCY=6000000
build_flags_ttgo_t_display = 
	${common.build_flags_lilygo_t_display}
	-D ARDUINO_LILYGO_T_DISPLAY
build_flags_bpi_leaf_s3 = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=0
	-D BATTERY
	-D SSD1306WIRE
build_flags_lilygo-t-display-s3 = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=0
	-D BOARD_HAS_PSRAM
	-D BATTERY
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER
	-D INIT_SEQUENCE_3
	-D CGRAM_OFFSET
	-D TFT_RGB_ORDER=TFT_RGB
	-D TFT_INVERSION_ON
	-D TFT_PARALLEL_8_BIT
	-D TFT_WIDTH=170
	-D TFT_HEIGHT=320
	-D TFT_CS=6
	-D TFT_DC=7
	-D TFT_RST=5
	-D TFT_WR=8
	-D TFT_RD=9
	-D TFT_D0=39
	-D TFT_D1=40
	-D TFT_D2=41
	-D TFT_D3=42
	-D TFT_D4=45
	-D TFT_D5=46
	-D TFT_D6=47
	-D TFT_D7=48
	-D TFT_BL=38
	-D TFT_BACKLIGHT_ON=HIGH
	-D LOAD_GLCD
	-D LOAD_GFXFF
	-D SMOOTH_FONT

[env]
platform = espressif32@3.5.0
framework = arduino
board = esp32dev
board_build.f_flash = 80000000L
board_build.partitions = src/partitions_no_ota.csv
build_type = release
lib_deps = ${common.lib_deps}
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	default

[env:esp32dev]
build_flags = 
	${common.build_flags}
	${common.build_flags_esp32}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0

[env:esp32doit-devkit-v1]
board = esp32doit-devkit-v1
build_flags = 
	${common.build_flags}
	${common.build_flags_esp32}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0

[env:esp32doit-devkit-v1-ble]
board = esp32doit-devkit-v1
build_flags = 
	${common.build_flags}
	${common.build_flags_esp32-ble}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0
board_build.partitions = src/partitions_ota.csv

[env:esp32doit-devkit-v1-wifi]
board = esp32doit-devkit-v1
build_flags = 
	${common.build_flags}
	${common.build_flags_esp32-wifi}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0
board_build.partitions = src/partitions_ota.csv

[env:esp-wrover-kit]
board = esp-wrover-kit
build_flags = 
	${common.build_flags}
	${common.build_flags_esp32}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0

[env:heltec_wifi_kit_32]
board = heltec_wifi_kit_32
build_flags = 
	${common.build_flags}
	${common.build_flags_heltec_wifi_kit_32}
lib_deps = 
	${common.lib_deps}
	HelTecAutomation/Heltec ESP32 Dev-Boards@1.1.2

[env:ttgo-t-eight]
build_flags = 
	${common.build_flags}
	${common.build_flags_ttgo_t_eight}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0

[env:ttgo-t-eight-ble]
build_flags = 
	${common.build_flags}
	${common.build_flags_ttgo_t_eight-ble}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0

[env:ttgo-t-eight-wifi]
build_flags = 
	${common.build_flags}
	${common.build_flags_ttgo_t_eight-wifi}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0

[env:ttgo-t-display]
build_flags = 
	${common.build_flags}
	${common.build_flags_ttgo_t_display}

[env:lilygo-t-display]
platform = espressif32@6.9.0
framework = arduino
board = lilygo-t-display
build_flags = 
	${common.build_flags}
	${common.build_flags_lilygo_t_display}

[env:lilygo-t-display-s3]
platform = espressif32@6.9.0
framework = arduino
board = lilygo-t-display-s3
board_build.partitions = src/partitions_lilygo-t-display-s3.csv
build_unflags = -D ARDUINO_USB_MODE=1
build_flags = 
	${common.build_flags}
	${common.build_flags_lilygo-t-display-s3}
lib_deps = 
	${common.lib_deps}
	adafruit/Adafruit TinyUSB Library@3.3.4

[env:bpi-leaf-s3]
platform = espressif32@6.9.0
framework = arduino
board = bpi_leaf_s3
board_build.partitions = src/partitions_bpi_leaf_s3.csv
build_flags = 
	${common.build_flags}
	${common.build_flags_bpi_leaf_s3}
lib_deps = 
	${common.lib_deps}
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.5.0
	adafruit/Adafruit TinyUSB Library@3.3.4
