name: Build firmware

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TMPDIR: /tmp

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO build on selected platforms
      run: |
        pio run -e esp32doit-devkit-v1
        pio run -t buildfs -e esp32doit-devkit-v1